-- Agregar campos de herramientas faltantes a la tabla asignacion
ALTER TABLE asignacion
ADD COLUMN asignacion_broca_3_8 VARCHAR(1) DEFAULT '0',
ADD COLUMN asignacion_broca_3_8_6_ran VARCHAR(1) DEFAULT '0',
ADD COLUMN asignacion_broca_1_2_6_ran VARCHAR(1) DEFAULT '0',
ADD COLUMN asignacion_broca_metal_madera_1_4 VARCHAR(1) DEFAULT '0',
ADD COLUMN asignacion_broca_metal_madera_3_8 VARCHAR(1) DEFAULT '0',
ADD COLUMN asignacion_broca_metal_madera_5_16 VARCHAR(1) DEFAULT '0',
ADD COLUMN asignacion_cajon_rojo VARCHAR(1) DEFAULT '0',
ADD COLUMN asignacion_cinta_de_senal VARCHAR(1) DEFAULT '0',
ADD COLUMN asignacion_cono_retractil VARCHAR(1) DEFAULT '0',
ADD COLUMN asignacion_espatula VARCHAR(1) DEFAULT '0',
ADD COLUMN asignacion_exten_de_corr_10_mts VARCHAR(1) DEFAULT '0',
ADD COLUMN asignacion_llave_locking_male VARCHAR(1) DEFAULT '0',
ADD COLUMN asignacion_llave_reliance VARCHAR(1) DEFAULT '0',
ADD COLUMN asignacion_llave_torque_rg_11 VARCHAR(1) DEFAULT '0',
ADD COLUMN asignacion_llave_torque_rg_6 VARCHAR(1) DEFAULT '0',
ADD COLUMN asignacion_llaves_mandril VARCHAR(1) DEFAULT '0',
ADD COLUMN asignacion_mandril_para_taladro VARCHAR(1) DEFAULT '0',
ADD COLUMN asignacion_pelacable_rg_6y_rg_11 VARCHAR(1) DEFAULT '0',
ADD COLUMN asignacion_pistola_de_silicona VARCHAR(1) DEFAULT '0',
ADD COLUMN asignacion_planillero VARCHAR(1) DEFAULT '0',
ADD COLUMN asignacion_puntas_para_multimetro VARCHAR(1) DEFAULT '0',
ADD COLUMN asignacion_sonda_metalica VARCHAR(1) DEFAULT '0',
ADD COLUMN asignacion_tacos_de_madera VARCHAR(1) DEFAULT '0',
ADD COLUMN asignacion_telefono_de_pruebas VARCHAR(1) DEFAULT '0',
ADD COLUMN asignacion_pelachaqueta VARCHAR(1) DEFAULT '0'; 